name: Detect secrets

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"


jobs:
  detect-secrets:
    uses: doovate/shared-workflows/.github/workflows/detect-secrets.yml@main
